// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type APIKey struct {
	Key         string `json:"key"`
	Description string `json:"description"`
	ExpiresAt   *int64 `json:"expiresAt,omitempty"`
	CreatedAt   int64  `json:"createdAt"`
}

type AddDocumentInput struct {
	Collection string       `json:"collection"`
	Key        string       `json:"key"`
	Lang       string       `json:"lang"`
	Meta       []*MetaInput `json:"meta,omitempty"`
	ContentMd  string       `json:"contentMd"`
	TTL        *int         `json:"ttl,omitempty"`
}

type AuthPayload struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expiresAt"`
}

type CollectionStats struct {
	Name           string `json:"name"`
	DocumentCount  int    `json:"documentCount"`
	RevisionCount  int    `json:"revisionCount"`
	MetaIndexCount int    `json:"metaIndexCount"`
}

type CreateAPIKeyInput struct {
	Description string `json:"description"`
	ExpiresAt   *int64 `json:"expiresAt,omitempty"`
}

type CreateGroupInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Members     []string `json:"members"`
}

type Document struct {
	ID        string         `json:"id"`
	Key       string         `json:"key"`
	Lang      string         `json:"lang"`
	Meta      map[string]any `json:"meta"`
	ContentMd string         `json:"contentMd"`
	AddedAt   int64          `json:"addedAt"`
	UpdatedAt int64          `json:"updatedAt"`
	ExpiresAt *int64         `json:"expiresAt,omitempty"`
}

type DocumentConnection struct {
	Edges      []*DocumentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type DocumentEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Document `json:"node"`
}

type FTSInput struct {
	Collection string `json:"collection"`
	Query      string `json:"query"`
	Limit      *int   `json:"limit,omitempty"`
}

type FTSResponse struct {
	Results []*FTSResult `json:"results"`
	Total   int          `json:"total"`
}

type FTSResult struct {
	Document     *Document `json:"document"`
	Score        float64   `json:"score"`
	MatchedTerms []string  `json:"matchedTerms"`
}

type Group struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Members     []string `json:"members"`
	CreatedAt   int64    `json:"createdAt"`
}

type GroupPermission struct {
	GroupName  string `json:"groupName"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type MetaInput struct {
	Key    string   `json:"key"`
	Values []string `json:"values"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RegisterWebhookInput struct {
	URL        string   `json:"url"`
	Events     []string `json:"events"`
	Collection string   `json:"collection"`
}

type Schema struct {
	Collection string `json:"collection"`
	Schema     string `json:"schema"`
	Enabled    bool   `json:"enabled"`
}

type SearchInput struct {
	Collection string       `json:"collection"`
	FilterMeta []*MetaInput `json:"filterMeta,omitempty"`
	Sort       *string      `json:"sort,omitempty"`
	Asc        *bool        `json:"asc,omitempty"`
	Limit      *int         `json:"limit,omitempty"`
	Offset     *int         `json:"offset,omitempty"`
}

type SetGroupPermissionInput struct {
	GroupName  string `json:"groupName"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type SetPermissionInput struct {
	Username   string `json:"username"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type SetSchemaInput struct {
	Collection string `json:"collection"`
	Schema     string `json:"schema"`
}

type Stats struct {
	DatabasePath     string             `json:"databasePath"`
	DatabaseSize     int                `json:"databaseSize"`
	Mode             string             `json:"mode"`
	Collections      []*CollectionStats `json:"collections"`
	TotalDocuments   int                `json:"totalDocuments"`
	TotalRevisions   int                `json:"totalRevisions"`
	TotalMetaIndices int                `json:"totalMetaIndices"`
}

type UpdateDocumentInput struct {
	Collection string       `json:"collection"`
	Key        string       `json:"key"`
	Lang       string       `json:"lang"`
	Meta       []*MetaInput `json:"meta,omitempty"`
	ContentMd  *string      `json:"contentMd,omitempty"`
}

type User struct {
	Username  string `json:"username"`
	Admin     bool   `json:"admin"`
	CreatedAt int64  `json:"createdAt"`
}

type UserPermission struct {
	Username   string `json:"username"`
	Collection string `json:"collection"`
	Read       bool   `json:"read"`
	Write      bool   `json:"write"`
	Admin      bool   `json:"admin"`
}

type ValidationResult struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
}

type VectorCollectionStats struct {
	Collection        string `json:"collection"`
	TotalDocuments    int    `json:"totalDocuments"`
	EmbeddedDocuments int    `json:"embeddedDocuments"`
}

type VectorSearchInput struct {
	Collection     string       `json:"collection"`
	Query          *string      `json:"query,omitempty"`
	QueryVector    []float64    `json:"queryVector,omitempty"`
	TopK           *int         `json:"topK,omitempty"`
	Threshold      *float64     `json:"threshold,omitempty"`
	FilterMeta     []*MetaInput `json:"filterMeta,omitempty"`
	IncludeContent *bool        `json:"includeContent,omitempty"`
}

type VectorSearchResponse struct {
	Results    []*VectorSearchResult `json:"results"`
	Total      int                   `json:"total"`
	Model      *string               `json:"model,omitempty"`
	Dimensions *int                  `json:"dimensions,omitempty"`
}

type VectorSearchResult struct {
	Document *Document `json:"document"`
	Score    float64   `json:"score"`
	Rank     int       `json:"rank"`
}

type VectorStats struct {
	Enabled     bool                     `json:"enabled"`
	Provider    *string                  `json:"provider,omitempty"`
	Model       *string                  `json:"model,omitempty"`
	Dimensions  *int                     `json:"dimensions,omitempty"`
	Collections []*VectorCollectionStats `json:"collections"`
	IndexReady  bool                     `json:"indexReady"`
}

type Webhook struct {
	ID         string   `json:"id"`
	URL        string   `json:"url"`
	Events     []string `json:"events"`
	Collection string   `json:"collection"`
	CreatedAt  int64    `json:"createdAt"`
}

type Permission string

const (
	PermissionRead  Permission = "READ"
	PermissionWrite Permission = "WRITE"
	PermissionAdmin Permission = "ADMIN"
)

var AllPermission = []Permission{
	PermissionRead,
	PermissionWrite,
	PermissionAdmin,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionRead, PermissionWrite, PermissionAdmin:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Permission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Permission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
