package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
)

// AddDocument is the resolver for the addDocument field.
func (r *mutationResolver) AddDocument(ctx context.Context, input AddDocumentInput) (*Document, error) {
	panic(fmt.Errorf("not implemented: AddDocument - addDocument"))
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, input UpdateDocumentInput) (*Document, error) {
	panic(fmt.Errorf("not implemented: UpdateDocument - updateDocument"))
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, collection string, key string, lang string) (bool, error) {
	if err := r.server.CheckPermission(ctx, collection, 1); err != nil { // 1 = Write
		return false, fmt.Errorf("permission denied: %w", err)
	}

	err := r.server.DeleteDocument(ctx, collection, key, lang)
	if err != nil {
		return false, fmt.Errorf("failed to delete document: %w", err)
	}

	return true, nil
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, collection string) (int, error) {
	panic(fmt.Errorf("not implemented: DeleteCollection - deleteCollection"))
}

// AddBatch is the resolver for the addBatch field.
func (r *mutationResolver) AddBatch(ctx context.Context, collection string, documents []*AddBatchDocumentInput) (*BatchAddResult, error) {
	panic(fmt.Errorf("not implemented: AddBatch - addBatch"))
}

// IngestDocuments is the resolver for the ingestDocuments field.
func (r *mutationResolver) IngestDocuments(ctx context.Context, collection string, documents []*IngestDocumentInput, options *IngestOptionsInput) (*IngestResult, error) {
	panic(fmt.Errorf("not implemented: IngestDocuments - ingestDocuments"))
}

// VectorReindex is the resolver for the vectorReindex field.
func (r *mutationResolver) VectorReindex(ctx context.Context, collection string, force *bool) (*VectorStats, error) {
	panic(fmt.Errorf("not implemented: VectorReindex - vectorReindex"))
}

// SetTTL is the resolver for the setTTL field.
func (r *mutationResolver) SetTTL(ctx context.Context, collection string, key string, lang string, ttl int) (*Document, error) {
	panic(fmt.Errorf("not implemented: SetTTL - setTTL"))
}

// ImportURL is the resolver for the importURL field.
func (r *mutationResolver) ImportURL(ctx context.Context, collection string, url string, key *string, lang string, meta []*MetaInput, ttl *int) (*Document, error) {
	panic(fmt.Errorf("not implemented: ImportURL - importURL"))
}

// RegisterWebhook is the resolver for the registerWebhook field.
func (r *mutationResolver) RegisterWebhook(ctx context.Context, input RegisterWebhookInput) (*Webhook, error) {
	panic(fmt.Errorf("not implemented: RegisterWebhook - registerWebhook"))
}

// DeleteWebhook is the resolver for the deleteWebhook field.
func (r *mutationResolver) DeleteWebhook(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteWebhook - deleteWebhook"))
}

// SetSchema is the resolver for the setSchema field.
func (r *mutationResolver) SetSchema(ctx context.Context, input SetSchemaInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SetSchema - setSchema"))
}

// DeleteSchema is the resolver for the deleteSchema field.
func (r *mutationResolver) DeleteSchema(ctx context.Context, collection string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSchema - deleteSchema"))
}

// ValidateDocument is the resolver for the validateDocument field.
func (r *mutationResolver) ValidateDocument(ctx context.Context, collection string, meta []*MetaInput) (*ValidationResult, error) {
	panic(fmt.Errorf("not implemented: ValidateDocument - validateDocument"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*AuthPayload, error) {
	userInfo, err := r.server.Authenticate(username, password)
	if err != nil {
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	token, expiresAt, err := r.server.GenerateJWT(userInfo.Username, userInfo.Admin)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &AuthPayload{
		Token:     token,
		ExpiresAt: expiresAt,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*User, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input CreateAPIKeyInput) (*APIKey, error) {
	panic(fmt.Errorf("not implemented: CreateAPIKey - createAPIKey"))
}

// SetPermission is the resolver for the setPermission field.
func (r *mutationResolver) SetPermission(ctx context.Context, input SetPermissionInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SetPermission - setPermission"))
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input CreateGroupInput) (*Group, error) {
	panic(fmt.Errorf("not implemented: CreateGroup - createGroup"))
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, name string, description string, members []string) (*Group, error) {
	panic(fmt.Errorf("not implemented: UpdateGroup - updateGroup"))
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, name string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGroup - deleteGroup"))
}

// SetGroupPermission is the resolver for the setGroupPermission field.
func (r *mutationResolver) SetGroupPermission(ctx context.Context, input SetGroupPermissionInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SetGroupPermission - setGroupPermission"))
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, collection string, key string, lang string, env map[string]any) (*Document, error) {
	panic(fmt.Errorf("not implemented: Document - document"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input SearchInput) (*DocumentConnection, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// VectorSearch is the resolver for the vectorSearch field.
func (r *queryResolver) VectorSearch(ctx context.Context, input VectorSearchInput) (*VectorSearchResponse, error) {
	panic(fmt.Errorf("not implemented: VectorSearch - vectorSearch"))
}

// VectorStats is the resolver for the vectorStats field.
func (r *queryResolver) VectorStats(ctx context.Context) (*VectorStats, error) {
	panic(fmt.Errorf("not implemented: VectorStats - vectorStats"))
}

// Fts is the resolver for the fts field.
func (r *queryResolver) Fts(ctx context.Context, input FTSInput) (*FTSResponse, error) {
	panic(fmt.Errorf("not implemented: Fts - fts"))
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*Stats, error) {
	panic(fmt.Errorf("not implemented: Stats - stats"))
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, collection *string) ([]*Webhook, error) {
	panic(fmt.Errorf("not implemented: Webhooks - webhooks"))
}

// Schema is the resolver for the schema field.
func (r *queryResolver) Schema(ctx context.Context, collection string) (*Schema, error) {
	panic(fmt.Errorf("not implemented: Schema - schema"))
}

// Schemas is the resolver for the schemas field.
func (r *queryResolver) Schemas(ctx context.Context) ([]*Schema, error) {
	panic(fmt.Errorf("not implemented: Schemas - schemas"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*Group, error) {
	panic(fmt.Errorf("not implemented: Groups - groups"))
}

// UserPermissions is the resolver for the userPermissions field.
func (r *queryResolver) UserPermissions(ctx context.Context, username string) ([]*UserPermission, error) {
	panic(fmt.Errorf("not implemented: UserPermissions - userPermissions"))
}

// GroupPermissions is the resolver for the groupPermissions field.
func (r *queryResolver) GroupPermissions(ctx context.Context, groupName string) ([]*GroupPermission, error) {
	panic(fmt.Errorf("not implemented: GroupPermissions - groupPermissions"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
