package fts

// Multi-language stop word lists for full-text search.
// Sources: stopwords-iso project, NLTK, and standard NLP stop word lists.

// defaultStopWordsPL contains common Polish stop words (~280 words).
var defaultStopWordsPL = map[string]bool{
	"a": true, "aby": true, "ach": true, "aczkolwiek": true, "aj": true, "albo": true,
	"ale": true, "ależ": true, "ani": true, "aż": true, "bardziej": true, "bardzo": true,
	"bez": true, "bo": true, "bowiem": true, "by": true, "byli": true, "być": true,
	"był": true, "była": true, "było": true, "były": true, "będą": true, "będzie": true,
	"chce": true, "choć": true, "ci": true, "cię": true, "ciebie": true, "co": true,
	"cokolwiek": true, "coraz": true, "coś": true, "czasami": true, "czasem": true,
	"czemu": true, "czy": true, "czyli": true, "daleko": true, "dla": true, "dlaczego": true,
	"dlatego": true, "do": true, "dobrze": true, "dokąd": true, "dość": true, "duże": true,
	"dużo": true, "dwa": true, "dwaj": true, "dwie": true, "dwoje": true, "dzisiaj": true,
	"dziś": true, "gdy": true, "gdyby": true, "gdyż": true, "gdzie": true,
	"gdziekolwiek": true, "gdzieś": true, "go": true, "ich": true, "ile": true,
	"im": true, "inna": true, "inne": true, "inny": true, "innych": true, "innym": true,
	"ja": true, "jak": true, "jakaś": true, "jakby": true, "jaki": true, "jakichś": true,
	"jakie": true, "jakiś": true, "jakiż": true, "jakkolwiek": true, "jako": true,
	"jakoś": true, "je": true, "jeden": true, "jedna": true, "jednak": true,
	"jednakże": true, "jedno": true, "jednym": true, "jego": true, "jej": true,
	"jemu": true, "jest": true, "jestem": true, "jeszcze": true, "jeśli": true,
	"jeżeli": true, "już": true, "ją": true, "każdy": true, "kiedy": true, "kilka": true,
	"kimś": true, "kto": true, "ktokolwiek": true, "ktoś": true, "która": true,
	"które": true, "którego": true, "której": true, "któremu": true, "który": true,
	"których": true, "którym": true, "którzy": true, "ku": true, "lat": true,
	"lecz": true, "lub": true, "ma": true, "mają": true, "mam": true, "mi": true,
	"miał": true, "mimo": true, "między": true, "mną": true, "mnie": true, "mogą": true,
	"moim": true, "moją": true, "moje": true, "może": true, "można": true, "mu": true,
	"musi": true, "my": true, "na": true, "nad": true, "nam": true, "nami": true,
	"nas": true, "nasi": true, "nasz": true, "nasza": true, "nasze": true, "naszego": true,
	"naszych": true, "natomiast": true, "nawet": true, "nic": true, "nich": true,
	"nie": true, "niech": true, "niego": true, "niej": true, "niemu": true,
	"nigdy": true, "nim": true, "nimi": true, "niż": true, "no": true, "nowe": true,
	"nowy": true, "nią": true, "od": true, "około": true, "on": true, "ona": true,
	"one": true, "oni": true, "ono": true, "obok": true, "ok": true,
	"oraz": true, "owszem": true, "pan": true, "pana": true, "pani": true, "po": true,
	"pod": true, "podczas": true, "pomimo": true, "ponad": true, "ponieważ": true,
	"powinien": true, "powinna": true, "powinni": true, "powinno": true, "poza": true,
	"prawie": true, "przed": true, "przede": true, "przedtem": true, "przez": true,
	"przy": true, "roku": true, "również": true, "sam": true, "sama": true, "się": true,
	"skąd": true, "sobie": true, "sobą": true, "sposób": true, "swoje": true, "są": true,
	"ta": true, "tak": true, "taka": true, "taką": true, "taki": true, "takich": true,
	"takie": true, "takiego": true, "także": true, "tam": true, "tamta": true,
	"tamte": true, "tamtego": true, "tamten": true, "tamtą": true, "te": true,
	"tego": true, "tej": true, "temu": true, "ten": true, "teraz": true, "też": true,
	"to": true, "tobie": true, "tobą": true, "trzeba": true, "tu": true, "tutaj": true,
	"twoi": true, "twoim": true, "twoja": true, "twoje": true, "twym": true,
	"twój": true, "ty": true, "tych": true, "tylko": true, "tym": true, "tys": true,
	"tzw": true, "tę": true, "więc": true, "więcej": true, "właśnie": true,
	"wszyscy": true, "wszystkich": true, "wszystkie": true, "wszystkim": true,
	"wszystko": true, "wtedy": true, "wy": true, "was": true, "wam": true, "wami": true,
	"wasz": true, "wasza": true, "wasze": true, "waszego": true, "waszych": true,
	"za": true, "zapewne": true, "zawsze": true, "zaś": true, "ze": true,
	"zeznowu": true, "że": true,
	"żeby": true, "żaden": true, "żadna": true, "żadne": true, "żadnych": true,
}

// defaultStopWordsDE contains common German stop words.
var defaultStopWordsDE = map[string]bool{
	"aber": true, "alle": true, "allem": true, "allen": true, "aller": true,
	"allerdings": true, "alles": true, "also": true, "am": true, "an": true,
	"ander": true, "andere": true, "anderem": true, "anderen": true, "anderer": true,
	"anderes": true, "anderm": true, "andern": true, "anders": true, "auch": true,
	"auf": true, "aus": true, "bei": true, "beim": true, "bin": true, "bis": true,
	"bist": true, "da": true, "damit": true, "dann": true, "dar": true, "darf": true,
	"darfst": true, "darin": true, "darum": true, "das": true, "dass": true,
	"daß": true, "dazu": true, "dein": true, "deine": true, "deinem": true,
	"deinen": true, "deiner": true, "dem": true, "den": true, "denn": true,
	"der": true, "deren": true, "des": true, "deshalb": true, "dessen": true,
	"die": true, "dies": true, "diese": true, "dieselbe": true, "dieselben": true,
	"diesem": true, "diesen": true, "dieser": true, "dieses": true, "doch": true,
	"dort": true, "du": true, "durch": true, "dürfen": true, "ein": true,
	"eine": true, "einem": true, "einen": true, "einer": true, "einige": true,
	"einigem": true, "einigen": true, "einiger": true, "einiges": true, "einmal": true,
	"er": true, "es": true, "etwas": true, "euch": true, "euer": true, "eure": true,
	"eurem": true, "euren": true, "eurer": true, "für": true, "gegen": true,
	"habe": true, "haben": true, "hat": true, "hatte": true, "hätte": true,
	"hier": true, "hin": true, "hinter": true, "ich": true, "ihm": true, "ihn": true,
	"ihnen": true, "ihr": true, "ihre": true, "ihrem": true, "ihren": true,
	"ihrer": true, "im": true, "in": true, "indem": true, "ins": true, "ist": true,
	"jede": true, "jedem": true, "jeden": true, "jeder": true, "jedes": true,
	"jedoch": true, "jenem": true, "jenen": true, "jener": true, "jenes": true,
	"jetzt": true, "kann": true, "kannst": true, "kein": true, "keine": true,
	"keinem": true, "keinen": true, "keiner": true, "man": true, "manche": true,
	"manchem": true, "manchen": true, "mancher": true, "manches": true, "mein": true,
	"meine": true, "meinem": true, "meinen": true, "meiner": true, "mit": true,
	"muss": true, "musste": true, "müssen": true, "nach": true, "nachdem": true,
	"nein": true, "nicht": true, "nichts": true, "noch": true, "nun": true, "nur": true,
	"ob": true, "oder": true, "ohne": true, "sehr": true, "sein": true, "seine": true,
	"seinem": true, "seinen": true, "seiner": true, "sich": true, "sie": true,
	"sind": true, "so": true, "sogar": true, "solche": true, "solchem": true,
	"solchen": true, "solcher": true, "soll": true, "sollen": true, "sollte": true,
	"sollten": true, "sondern": true, "sonst": true, "über": true, "um": true,
	"und": true, "uns": true, "unser": true, "unsere": true, "unserem": true,
	"unseren": true, "unserer": true, "unter": true, "viel": true, "vom": true,
	"von": true, "vor": true, "während": true, "war": true, "warum": true,
	"was": true, "weil": true, "welch": true, "welche": true, "welchem": true,
	"welchen": true, "welcher": true, "welches": true, "wenn": true, "wer": true,
	"werde": true, "werden": true, "wie": true, "wieder": true, "will": true,
	"wir": true, "wird": true, "wo": true, "wollen": true, "wollte": true,
	"würde": true, "würden": true, "zu": true, "zum": true, "zur": true,
	"zwar": true, "zwischen": true,
}

// defaultStopWordsFR contains common French stop words.
var defaultStopWordsFR = map[string]bool{
	"ai": true, "au": true, "aura": true, "aurai": true, "auraient": true,
	"aurais": true, "aurait": true, "auras": true, "aurez": true, "auriez": true,
	"aurions": true, "aurons": true, "auront": true, "aux": true, "avaient": true,
	"avais": true, "avait": true, "avec": true, "avez": true, "aviez": true,
	"avions": true, "avons": true, "ayant": true, "ayez": true, "ayons": true,
	"ce": true, "ces": true, "dans": true, "de": true, "des": true, "du": true,
	"elle": true, "en": true, "es": true, "est": true, "et": true, "eu": true,
	"eue": true, "eues": true, "eus": true, "eusse": true, "eussent": true,
	"eusses": true, "eussiez": true, "eussions": true, "eut": true, "eux": true,
	"eûmes": true, "eût": true, "eûtes": true, "furent": true, "fus": true,
	"fusse": true, "fussent": true, "fusses": true, "fussiez": true, "fussions": true,
	"fut": true, "fûmes": true, "fût": true, "fûtes": true, "il": true, "ils": true,
	"je": true, "la": true, "le": true, "les": true, "leur": true, "leurs": true,
	"lui": true, "ma": true, "mais": true, "me": true, "mes": true, "moi": true,
	"mon": true, "même": true, "ni": true, "nos": true, "notre": true, "nous": true,
	"on": true, "ont": true, "ou": true, "par": true, "pas": true, "pour": true,
	"qu": true, "que": true, "quel": true, "quelle": true, "quelles": true,
	"quels": true, "qui": true, "sa": true, "sans": true, "se": true, "sera": true,
	"serai": true, "seraient": true, "serais": true, "serait": true, "seras": true,
	"serez": true, "seriez": true, "serions": true, "serons": true, "seront": true,
	"ses": true, "soi": true, "soient": true, "sois": true, "soit": true,
	"sommes": true, "son": true, "sont": true, "soyez": true, "soyons": true,
	"suis": true, "sur": true, "ta": true, "te": true, "tes": true, "toi": true,
	"ton": true, "tu": true, "un": true, "une": true, "vos": true, "votre": true,
	"vous": true, "étaient": true, "étais": true, "était": true, "étant": true,
	"étiez": true, "étions": true, "été": true, "êtes": true,
}

// defaultStopWordsES contains common Spanish stop words.
var defaultStopWordsES = map[string]bool{
	"al": true, "algo": true, "algunas": true, "alguno": true, "algunos": true,
	"algún": true, "ante": true, "antes": true, "aquel": true, "aquellas": true,
	"aquellos": true, "aquí": true, "así": true, "como": true, "con": true,
	"contra": true, "cual": true, "cuando": true, "de": true, "del": true,
	"desde": true, "donde": true, "durante": true, "el": true, "ella": true,
	"ellas": true, "ellos": true, "en": true, "entre": true, "era": true,
	"esa": true, "esas": true, "ese": true, "eso": true, "esos": true,
	"esta": true, "estaba": true, "estado": true, "estar": true, "estas": true,
	"este": true, "esto": true, "estos": true, "está": true, "están": true,
	"fue": true, "fuera": true, "fueron": true, "ha": true, "había": true,
	"han": true, "hasta": true, "hay": true, "la": true, "las": true, "le": true,
	"les": true, "lo": true, "los": true, "más": true, "me": true, "mi": true,
	"mientras": true, "muy": true, "mí": true, "nada": true,
	"ni": true, "no": true, "nos": true, "nosotros": true, "nuestro": true,
	"nuestra": true, "nuestros": true, "nuestras": true, "otra": true,
	"otras": true, "otro": true, "otros": true, "para": true, "pero": true,
	"poco": true, "por": true, "porque": true, "qué": true, "que": true,
	"quien": true, "se": true, "sea": true, "ser": true, "si": true, "sin": true,
	"sino": true, "sobre": true, "somos": true, "son": true, "soy": true,
	"su": true, "sus": true, "también": true, "te": true, "tengo": true,
	"ti": true, "tiene": true, "tienen": true, "toda": true, "todas": true,
	"todo": true, "todos": true, "tu": true, "tus": true, "tú": true, "un": true,
	"una": true, "uno": true, "unos": true, "usted": true, "ustedes": true,
	"ya": true, "yo": true,
}

// defaultStopWordsIT contains common Italian stop words.
var defaultStopWordsIT = map[string]bool{
	"ad": true, "al": true, "allo": true, "ai": true, "agli": true, "alle": true,
	"con": true, "col": true, "coi": true, "da": true, "dal": true, "dallo": true,
	"dai": true, "dagli": true, "dalle": true, "di": true, "del": true,
	"dello": true, "dei": true, "degli": true, "delle": true, "in": true,
	"nel": true, "nello": true, "nei": true, "negli": true, "nelle": true,
	"su": true, "sul": true, "sullo": true, "sui": true, "sugli": true,
	"sulle": true, "per": true, "tra": true, "contro": true, "io": true,
	"tu": true, "lui": true, "lei": true, "noi": true, "voi": true, "loro": true,
	"mio": true, "mia": true, "miei": true, "mie": true, "tuo": true, "tua": true,
	"tuoi": true, "tue": true, "suo": true, "sua": true, "suoi": true, "sue": true,
	"nostro": true, "nostra": true, "nostri": true, "nostre": true, "vostro": true,
	"vostra": true, "vostri": true, "vostre": true, "mi": true, "ti": true,
	"ci": true, "vi": true, "lo": true, "la": true, "li": true, "le": true,
	"gli": true, "ne": true, "il": true, "un": true, "uno": true, "una": true,
	"ma": true, "ed": true, "se": true, "perché": true, "anche": true, "come": true,
	"dove": true, "che": true, "chi": true, "cui": true, "non": true, "più": true,
	"quale": true, "quanto": true, "quanti": true, "quanta": true, "quante": true,
	"quello": true, "quelli": true, "quella": true, "quelle": true, "questo": true,
	"questi": true, "questa": true, "queste": true, "si": true, "tutto": true,
	"tutti": true, "ha": true, "hanno": true, "abbia": true, "abbiano": true,
	"avere": true, "avesse": true, "avuto": true, "essere": true, "sono": true,
	"sia": true, "stato": true, "stati": true, "stata": true, "state": true,
	"sarà": true, "sarebbe": true, "era": true, "erano": true, "fatto": true,
	"fa": true, "fare": true, "quando": true, "solo": true, "già": true,
	"ancora": true, "dopo": true, "prima": true, "poi": true, "molto": true,
	"ogni": true, "altro": true, "altri": true, "altra": true,
	"altre": true, "stesso": true, "stessa": true, "stessi": true, "stesse": true,
	"senza": true, "sopra": true, "sotto": true, "fra": true, "fino": true,
}

// defaultStopWordsPT contains common Portuguese stop words.
var defaultStopWordsPT = map[string]bool{
	"ao": true, "aos": true, "aquela": true, "aquelas": true, "aquele": true,
	"aqueles": true, "aquilo": true, "as": true, "até": true, "com": true,
	"como": true, "da": true, "das": true, "de": true, "dela": true, "delas": true,
	"dele": true, "deles": true, "depois": true, "do": true, "dos": true, "ela": true,
	"elas": true, "ele": true, "eles": true, "em": true, "entre": true, "era": true,
	"essa": true, "essas": true, "esse": true, "esses": true, "esta": true,
	"estas": true, "este": true, "estes": true, "eu": true, "foi": true,
	"foram": true, "há": true, "isso": true, "isto": true, "já": true, "lhe": true,
	"lhes": true, "mais": true, "mas": true, "me": true, "mesmo": true, "meu": true,
	"meus": true, "minha": true, "minhas": true, "muito": true, "na": true,
	"nas": true, "nem": true, "no": true, "nos": true, "nosso": true, "nossa": true,
	"nossos": true, "nossas": true, "num": true, "numa": true, "não": true,
	"nós": true, "os": true, "ou": true, "para": true, "pela": true, "pelas": true,
	"pelo": true, "pelos": true, "por": true, "qual": true, "quando": true,
	"que": true, "quem": true, "se": true, "sem": true, "seu": true, "seus": true,
	"sua": true, "suas": true, "são": true, "só": true, "também": true, "te": true,
	"tem": true, "teu": true, "teus": true, "tu": true, "tua": true, "tuas": true,
	"tém": true, "um": true, "uma": true, "uns": true, "você": true, "vocês": true,
	"vos": true, "vosso": true, "vossa": true, "à": true,
}

// defaultStopWordsNL contains common Dutch stop words.
var defaultStopWordsNL = map[string]bool{
	"aan": true, "al": true, "alles": true, "als": true, "altijd": true,
	"andere": true, "ben": true, "bij": true, "daar": true, "dan": true,
	"dat": true, "de": true, "der": true, "deze": true, "die": true, "dit": true,
	"doch": true, "doen": true, "door": true, "dus": true, "een": true, "eens": true,
	"en": true, "er": true, "ge": true, "geen": true, "geweest": true, "haar": true,
	"had": true, "heb": true, "hebben": true, "heeft": true, "hem": true, "het": true,
	"hier": true, "hij": true, "hoe": true, "hun": true, "iemand": true, "iets": true,
	"ik": true, "in": true, "is": true, "ja": true, "je": true, "kan": true,
	"kon": true, "kunnen": true, "maar": true, "me": true, "meer": true, "men": true,
	"met": true, "mij": true, "mijn": true, "moet": true, "na": true, "naar": true,
	"niet": true, "niets": true, "nog": true, "nu": true, "of": true, "om": true,
	"omdat": true, "ons": true, "onze": true, "ook": true, "op": true, "over": true,
	"reeds": true, "te": true, "tegen": true, "toch": true, "toen": true, "tot": true,
	"u": true, "uit": true, "uw": true, "van": true, "veel": true, "voor": true,
	"want": true, "waren": true, "was": true, "wat": true, "we": true, "wel": true,
	"werd": true, "wij": true, "wil": true, "worden": true, "wordt": true,
	"zal": true, "ze": true, "zelf": true, "zich": true, "zij": true, "zijn": true,
	"zo": true, "zou": true, "zonder": true,
}

// defaultStopWordsRU contains common Russian stop words.
var defaultStopWordsRU = map[string]bool{
	"а": true, "без": true, "более": true, "больше": true, "будет": true,
	"будто": true, "бы": true, "был": true, "была": true, "были": true,
	"было": true, "быть": true, "в": true, "вам": true, "вас": true,
	"ведь": true, "весь": true, "во": true, "вот": true, "все": true,
	"всего": true, "всех": true, "вся": true, "всё": true, "вы": true,
	"где": true, "да": true, "даже": true, "для": true, "до": true, "его": true,
	"ее": true, "ей": true, "ему": true, "если": true, "есть": true,
	"ещё": true, "же": true, "за": true, "здесь": true, "и": true, "из": true,
	"или": true, "им": true, "их": true, "к": true, "как": true, "когда": true,
	"кто": true, "ли": true, "меня": true, "мне": true, "мной": true,
	"мог": true, "может": true, "можно": true, "мой": true, "моя": true,
	"мы": true, "на": true, "над": true, "надо": true, "нам": true, "нас": true,
	"наш": true, "не": true, "него": true, "нее": true, "ней": true,
	"нельзя": true, "нет": true, "ни": true, "них": true, "но": true,
	"ну": true, "нём": true, "о": true, "об": true, "один": true, "он": true,
	"она": true, "они": true, "оно": true, "от": true, "очень": true,
	"по": true, "под": true, "после": true, "потому": true, "почти": true,
	"при": true, "про": true, "раз": true, "разве": true, "с": true,
	"сам": true, "свой": true, "себе": true, "себя": true, "сейчас": true,
	"со": true, "совсем": true, "так": true, "также": true, "такой": true,
	"там": true, "тебе": true, "тебя": true, "тем": true, "теперь": true,
	"то": true, "тоже": true, "только": true, "тот": true, "ту": true,
	"ты": true, "у": true, "уж": true, "уже": true, "хоть": true, "чего": true,
	"чем": true, "через": true, "что": true, "чтобы": true, "чуть": true,
	"эти": true, "этих": true, "это": true, "этого": true, "этой": true,
	"этом": true, "этот": true, "эту": true, "я": true,
}

// defaultStopWordsSV contains common Swedish stop words.
var defaultStopWordsSV = map[string]bool{
	"alla": true, "allt": true, "att": true, "av": true, "blev": true,
	"bli": true, "blir": true, "blivit": true, "de": true, "dem": true,
	"den": true, "denna": true, "deras": true, "dess": true, "dessa": true,
	"det": true, "detta": true, "dig": true, "din": true, "dina": true,
	"dit": true, "du": true, "där": true, "då": true, "efter": true, "ej": true,
	"eller": true, "en": true, "er": true, "era": true, "ert": true, "ett": true,
	"från": true, "för": true, "ha": true, "hade": true, "han": true, "hans": true,
	"har": true, "hen": true, "hennes": true, "hon": true, "honom": true,
	"hur": true, "här": true, "inte": true, "jag": true, "ju": true, "kan": true,
	"kunde": true, "man": true, "med": true, "mellan": true, "men": true,
	"mig": true, "min": true, "mina": true, "mitt": true, "mot": true,
	"mycket": true, "ni": true, "nu": true, "när": true, "någon": true,
	"något": true, "några": true, "och": true, "om": true, "oss": true,
	"på": true, "samma": true, "sedan": true, "sig": true, "sin": true,
	"sina": true, "sitt": true, "ska": true, "skall": true, "skulle": true,
	"som": true, "så": true, "till": true, "under": true, "upp": true,
	"ut": true, "utan": true, "var": true, "vara": true, "vart": true,
	"vem": true, "vi": true, "vid": true, "vilka": true, "vilken": true,
	"vilket": true, "vill": true, "vår": true, "våra": true, "vårt": true,
	"än": true, "är": true, "åt": true, "över": true,
}

// defaultStopWordsNO contains common Norwegian stop words.
var defaultStopWordsNO = map[string]bool{
	"alle": true, "at": true, "av": true, "bare": true, "begge": true,
	"ble": true, "blei": true, "bli": true, "blir": true, "blitt": true,
	"da": true, "de": true, "deg": true, "dei": true, "deira": true,
	"den": true, "denne": true, "der": true, "dere": true, "deres": true,
	"det": true, "dette": true, "di": true, "din": true, "disse": true,
	"du": true, "dykk": true, "dykkar": true, "då": true, "eit": true,
	"eller": true, "en": true, "enn": true, "er": true, "et": true, "ett": true,
	"etter": true, "for": true, "fordi": true, "fra": true, "før": true,
	"ha": true, "hadde": true, "han": true, "hans": true, "har": true,
	"hennar": true, "henne": true, "hennes": true, "her": true, "hjå": true,
	"ho": true, "hoe": true, "honom": true, "hun": true, "hva": true,
	"hvor": true, "i": true, "ikke": true, "ingen": true, "ingi": true,
	"inkje": true, "inn": true, "ja": true, "jeg": true, "kan": true,
	"kom": true, "kunne": true, "kva": true, "kvar": true, "kvifor": true,
	"man": true, "mange": true, "me": true, "med": true, "meg": true,
	"mellom": true, "men": true, "mi": true, "min": true, "mine": true,
	"mitt": true, "mot": true, "mykje": true, "noko": true, "nokon": true,
	"nokre": true, "nå": true, "når": true,
	"og": true, "også": true, "om": true, "opp": true, "oss": true, "over": true,
	"på": true, "seg": true, "si": true, "sia": true, "sidan": true, "sin": true,
	"sine": true, "sitt": true, "sjøl": true, "skal": true, "skulle": true,
	"so": true, "som": true, "somme": true, "somt": true, "så": true,
	"til": true, "um": true, "under": true, "upp": true, "ut": true, "var": true,
	"vart": true, "vere": true, "ved": true, "vi": true, "vil": true,
	"ville": true, "vore": true, "vors": true, "vort": true, "vår": true,
	"være": true,
}

// defaultStopWordsDA contains common Danish stop words.
var defaultStopWordsDA = map[string]bool{
	"af": true, "alle": true, "alt": true, "anden": true, "at": true,
	"blev": true, "blive": true, "bliver": true, "da": true, "de": true,
	"dem": true, "den": true, "denne": true, "der": true, "deres": true,
	"det": true, "dette": true, "dig": true, "din": true, "dine": true,
	"disse": true, "dog": true, "du": true, "efter": true, "eller": true,
	"en": true, "end": true, "er": true, "et": true, "for": true, "fra": true,
	"få": true, "får": true, "got": true, "ha": true, "had": true, "han": true,
	"hans": true, "har": true, "have": true, "hende": true, "hendes": true,
	"her": true, "hos": true, "hun": true, "hvad": true, "hvis": true,
	"hvor": true, "i": true, "ikke": true, "ind": true, "ingen": true,
	"intet": true, "jeg": true, "jer": true, "jeres": true, "jo": true,
	"kan": true, "kom": true, "kunne": true, "man": true, "mange": true,
	"med": true, "meget": true, "men": true, "mig": true, "min": true,
	"mine": true, "mit": true, "mod": true, "ned": true, "noget": true,
	"nogen": true, "nu": true, "når": true, "og": true,
	"også": true, "om": true, "op": true, "os": true, "over": true,
	"på": true, "selv": true, "sig": true, "sin": true, "sine": true,
	"sit": true, "skal": true, "skulle": true, "som": true, "til": true,
	"ud": true, "under": true, "var": true, "vi": true, "vil": true,
	"ville": true, "vor": true, "vores": true, "være": true,
}

// defaultStopWordsFI contains common Finnish stop words.
var defaultStopWordsFI = map[string]bool{
	"ei": true, "eivät": true, "emme": true, "en": true, "et": true,
	"ette": true, "että": true, "he": true, "heidän": true, "heihin": true,
	"heille": true, "heiltä": true, "heissä": true, "heistä": true,
	"heitä": true, "hän": true, "hänen": true, "häneen": true, "hänelle": true,
	"häneltä": true, "hänessä": true, "hänestä": true, "häntä": true,
	"itse": true, "ja": true, "jo": true, "jos": true, "joka": true,
	"jonka": true, "jossa": true, "josta": true, "jota": true, "jotka": true,
	"joiden": true, "joita": true, "kanssa": true, "kun": true, "kuin": true,
	"me": true, "meidän": true, "meihin": true, "meille": true, "meiltä": true,
	"meissä": true, "meistä": true, "meitä": true, "minun": true,
	"minulle": true, "minulta": true, "minussa": true, "minusta": true,
	"minä": true, "minut": true, "mitä": true, "mukaan": true, "mutta": true,
	"ne": true, "niin": true, "nyt": true, "oli": true, "olemme": true,
	"olen": true, "olet": true, "olette": true, "olivat": true, "olla": true,
	"ollut": true, "on": true, "ovat": true, "poikki": true, "se": true,
	"sekä": true, "sen": true, "siihen": true, "sillä": true, "sinun": true,
	"sinulle": true, "sinulta": true, "sinussa": true, "sinusta": true,
	"sinä": true, "sinut": true, "sitä": true, "tai": true, "te": true,
	"teidän": true, "teihin": true, "teille": true, "teiltä": true,
	"teissä": true, "teistä": true, "teitä": true, "tuo": true, "tämä": true,
	"tämän": true, "tässä": true, "tästä": true, "tätä": true, "vaan": true,
	"vai": true, "vain": true, "välillä": true,
}

// defaultStopWordsHU contains common Hungarian stop words.
var defaultStopWordsHU = map[string]bool{
	"a": true, "ahogy": true, "ahol": true, "aki": true, "akik": true,
	"akkor": true, "alatt": true, "ami": true, "amit": true, "amolyan": true,
	"az": true, "aztán": true, "azután": true, "amikor": true, "át": true,
	"be": true, "belül": true, "benne": true, "bár": true, "csak": true,
	"de": true, "e": true, "ebben": true, "eddig": true, "egy": true,
	"egyes": true, "egyetlen": true, "egyik": true, "egyre": true, "el": true,
	"ellen": true, "elsö": true, "elég": true, "elöl": true, "elött": true,
	"emilyen": true, "engem": true, "ennek": true, "erre": true, "ez": true,
	"ezek": true, "ezen": true, "ezt": true, "fel": true, "felé": true,
	"hanem": true, "hiszen": true, "hogy": true, "hogyan": true, "ide": true,
	"igen": true, "így": true, "ill": true, "is": true, "ison": true, "itt": true,
	"jobban": true, "jól": true, "kell": true, "keresztül": true, "ki": true,
	"kívül": true, "között": true, "közül": true, "le": true, "legyen": true,
	"lehet": true, "lenne": true, "lenni": true, "lesz": true, "már": true,
	"meg": true, "mellett": true, "mely": true, "melyek": true, "mert": true,
	"mi": true, "miatt": true, "mikor": true, "milyen": true, "mind": true,
	"minden": true, "mindenki": true, "mint": true, "mintha": true, "mit": true,
	"mivel": true, "még": true, "más": true, "máshol": true,
	"másik": true, "na": true, "nagy": true, "nagyon": true, "ne": true,
	"nekem": true, "neki": true, "nem": true, "nincs": true, "néha": true,
	"néhány": true, "nélkül": true, "oda": true, "olyan": true, "ott": true,
	"pedig": true, "persze": true, "rá": true, "s": true, "saját": true,
	"sem": true, "semmi": true, "sok": true, "sokat": true, "te": true,
	"tehát": true, "teljes": true, "tovább": true, "továbbá": true, "tudni": true,
	"tudom": true, "tán": true, "több": true, "ugyan": true, "ugyanis": true,
	"utolsó": true, "után": true, "utána": true, "vagy": true, "vagyis": true,
	"valaki": true, "valami": true, "van": true, "vannak": true, "vele": true,
	"vissza": true, "volt": true, "volna": true, "és": true, "én": true,
	"ö": true, "ön": true, "össze": true, "úgy": true,
}

// defaultStopWordsRO contains common Romanian stop words.
var defaultStopWordsRO = map[string]bool{
	"acea": true, "aceasta": true, "această": true, "aceea": true, "acei": true,
	"aceia": true, "acel": true, "acela": true, "acele": true, "acelea": true,
	"acest": true, "acesta": true, "aceste": true, "acestea": true, "aceşti": true,
	"aceştia": true, "acolo": true, "acum": true, "ai": true, "aici": true,
	"al": true, "ale": true, "alea": true, "alt": true, "alta": true,
	"alte": true, "altele": true, "alţi": true, "alţii": true, "ar": true,
	"are": true, "aş": true, "au": true, "avea": true, "avem": true,
	"aveţi": true, "ca": true, "care": true, "ce": true, "cel": true,
	"ceva": true, "ci": true, "cine": true, "cu": true, "cum": true,
	"dacă": true, "dar": true, "de": true, "deja": true, "deşi": true,
	"din": true, "după": true, "ea": true, "ei": true, "el": true, "ele": true,
	"eram": true, "este": true, "eu": true, "fi": true, "fie": true,
	"fiecare": true, "fiind": true, "fără": true, "iar": true, "ieri": true,
	"la": true, "le": true, "li": true, "lor": true, "lui": true, "mai": true,
	"mea": true, "mei": true, "mele": true, "meu": true, "mi": true,
	"mine": true, "mult": true, "multă": true, "mulţi": true, "mulţumesc": true,
	"ne": true, "nici": true, "nimeni": true, "nimic": true, "noi": true,
	"nostru": true, "noastră": true, "nu": true, "o": true, "ori": true,
	"orice": true, "oriunde": true, "pe": true, "pentru": true, "peste": true,
	"poate": true, "prin": true, "puţin": true, "sa": true, "sau": true,
	"se": true, "si": true, "sunt": true, "suntem": true, "să": true,
	"ta": true, "te": true, "tine": true, "toată": true, "toate": true,
	"tot": true, "toţi": true, "tu": true, "un": true, "una": true,
	"unde": true, "undeva": true, "unele": true, "unor": true, "voi": true,
	"voastră": true, "vostru": true, "vă": true, "în": true, "între": true,
	"îl": true, "îmi": true, "îi": true, "şi": true,
}

// defaultStopWordsTR contains common Turkish stop words.
var defaultStopWordsTR = map[string]bool{
	"acaba": true, "ama": true, "ancak": true, "arada": true, "aslında": true,
	"ayrıca": true, "bana": true, "bazı": true, "belki": true, "ben": true,
	"benden": true, "beni": true, "benim": true, "beri": true, "bile": true,
	"bir": true, "birçok": true, "biri": true, "birkaç": true, "birşey": true,
	"biz": true, "bizden": true, "bize": true, "bizi": true, "bizim": true,
	"bu": true, "buna": true, "bunda": true, "bundan": true, "bunlar": true,
	"bunları": true, "bunların": true, "bunu": true, "bunun": true, "böyle": true,
	"böylece": true, "da": true, "daha": true, "dahi": true, "de": true,
	"defa": true, "değil": true, "diye": true, "diğer": true, "dolayı": true,
	"elbette": true, "en": true, "fakat": true, "gibi": true, "göre": true,
	"hala": true, "halde": true, "hangi": true, "hem": true, "henüz": true,
	"hep": true, "hepsi": true, "her": true, "herhangi": true, "herkes": true,
	"hiç": true, "hiçbir": true, "için": true, "ile": true, "ise": true,
	"kendi": true, "kendine": true, "kendini": true, "ki": true, "kim": true,
	"kime": true, "kimi": true, "kimse": true, "mu": true, "mı": true,
	"nasıl": true, "ne": true, "neden": true, "nerede": true, "nereye": true,
	"niye": true, "niçin": true, "ona": true, "ondan": true, "onlar": true,
	"onlardan": true, "onlara": true, "onları": true, "onların": true,
	"onu": true, "onun": true, "orada": true, "oysa": true, "sanki": true,
	"sen": true, "senden": true, "seni": true, "senin": true, "siz": true,
	"sizden": true, "size": true, "sizi": true, "sizin": true, "şey": true,
	"şu": true, "şuna": true, "şundan": true, "şunu": true, "tüm": true,
	"var": true, "ve": true, "veya": true, "ya": true, "yani": true,
	"yok": true,
}

// defaultStopWordsAR contains common Arabic stop words.
var defaultStopWordsAR = map[string]bool{
	"من": true, "في": true, "على": true, "إلى": true, "عن": true,
	"أن": true, "هذا": true, "التي": true, "الذي": true, "هو": true,
	"هي": true, "كان": true, "لا": true, "ما": true, "مع": true,
	"و": true, "أو": true, "كل": true, "ذلك": true, "بين": true,
	"قد": true, "بعد": true, "ثم": true, "لم": true, "لن": true,
	"حتى": true, "لكن": true, "هل": true, "إن": true, "أي": true,
	"كيف": true, "أنا": true, "نحن": true, "أنت": true, "هم": true,
	"هن": true, "أنتم": true, "فيها": true, "منها": true, "عليها": true,
	"عليه": true, "منه": true, "فيه": true, "به": true, "بها": true,
	"لها": true, "له": true, "عند": true, "غير": true, "بعض": true,
	"إذا": true, "كما": true, "أيضا": true, "منذ": true, "قبل": true,
	"حين": true, "عبر": true, "فقط": true, "ليس": true, "هنا": true,
	"هناك": true, "تلك": true, "هذه": true, "تم": true, "وقد": true,
	"ولا": true, "وهو": true, "وهي": true,
}
