version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
  exclusions:
    rules:
      - path: graphql/generated.go
        linters:
          - gosec
          - errcheck
