// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: proto/mddb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MDDB_Add_FullMethodName              = "/mddb.MDDB/Add"
	MDDB_AddBatch_FullMethodName         = "/mddb.MDDB/AddBatch"
	MDDB_DeleteBatch_FullMethodName      = "/mddb.MDDB/DeleteBatch"
	MDDB_UpdateBatch_FullMethodName      = "/mddb.MDDB/UpdateBatch"
	MDDB_Get_FullMethodName              = "/mddb.MDDB/Get"
	MDDB_Search_FullMethodName           = "/mddb.MDDB/Search"
	MDDB_Export_FullMethodName           = "/mddb.MDDB/Export"
	MDDB_Backup_FullMethodName           = "/mddb.MDDB/Backup"
	MDDB_Restore_FullMethodName          = "/mddb.MDDB/Restore"
	MDDB_Truncate_FullMethodName         = "/mddb.MDDB/Truncate"
	MDDB_Stats_FullMethodName            = "/mddb.MDDB/Stats"
	MDDB_VectorSearch_FullMethodName     = "/mddb.MDDB/VectorSearch"
	MDDB_VectorReindex_FullMethodName    = "/mddb.MDDB/VectorReindex"
	MDDB_VectorStats_FullMethodName      = "/mddb.MDDB/VectorStats"
	MDDB_ImportURL_FullMethodName        = "/mddb.MDDB/ImportURL"
	MDDB_SetTTL_FullMethodName           = "/mddb.MDDB/SetTTL"
	MDDB_FTS_FullMethodName              = "/mddb.MDDB/FTS"
	MDDB_HybridSearch_FullMethodName     = "/mddb.MDDB/HybridSearch"
	MDDB_RegisterWebhook_FullMethodName  = "/mddb.MDDB/RegisterWebhook"
	MDDB_ListWebhooks_FullMethodName     = "/mddb.MDDB/ListWebhooks"
	MDDB_DeleteWebhook_FullMethodName    = "/mddb.MDDB/DeleteWebhook"
	MDDB_SetSchema_FullMethodName        = "/mddb.MDDB/SetSchema"
	MDDB_GetSchema_FullMethodName        = "/mddb.MDDB/GetSchema"
	MDDB_DeleteSchema_FullMethodName     = "/mddb.MDDB/DeleteSchema"
	MDDB_ListSchemas_FullMethodName      = "/mddb.MDDB/ListSchemas"
	MDDB_ValidateDocument_FullMethodName = "/mddb.MDDB/ValidateDocument"
)

// MDDBClient is the client API for MDDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MDDB Service - gRPC API for Markdown Database
type MDDBClient interface {
	// Add or update a document
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Document, error)
	// Add or update multiple documents in a single transaction (batch)
	AddBatch(ctx context.Context, in *AddBatchRequest, opts ...grpc.CallOption) (*AddBatchResponse, error)
	// Delete multiple documents in a single transaction (batch)
	DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error)
	// Update multiple documents in a single transaction (batch)
	UpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*UpdateBatchResponse, error)
	// Get a document by key and language
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error)
	// Search documents with filters
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Export documents (streaming)
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error)
	// Create database backup
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	// Restore database from backup
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// Truncate revision history
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error)
	// Get server statistics
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Vector/semantic search using embeddings
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	// Reindex embeddings for a collection
	VectorReindex(ctx context.Context, in *VectorReindexRequest, opts ...grpc.CallOption) (*VectorReindexResponse, error)
	// Get vector/embedding statistics
	VectorStats(ctx context.Context, in *VectorStatsRequest, opts ...grpc.CallOption) (*VectorStatsResponse, error)
	// Import document from URL
	ImportURL(ctx context.Context, in *ImportURLRequest, opts ...grpc.CallOption) (*Document, error)
	// Set TTL on a document
	SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*Document, error)
	// Full-text search
	FTS(ctx context.Context, in *FTSRequest, opts ...grpc.CallOption) (*FTSResponse, error)
	// Hybrid search (combines FTS + vector search)
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// Register a webhook
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookProto, error)
	// List webhooks
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	// Delete a webhook
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error)
	// Set JSON Schema for a collection's metadata validation
	SetSchema(ctx context.Context, in *SetSchemaRequest, opts ...grpc.CallOption) (*SetSchemaResponse, error)
	// Get JSON Schema for a collection
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// Delete JSON Schema for a collection (disables validation)
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	// List all collection schemas
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// Validate document metadata against collection schema
	ValidateDocument(ctx context.Context, in *ValidateDocumentRequest, opts ...grpc.CallOption) (*ValidateDocumentResponse, error)
}

type mDDBClient struct {
	cc grpc.ClientConnInterface
}

func NewMDDBClient(cc grpc.ClientConnInterface) MDDBClient {
	return &mDDBClient{cc}
}

func (c *mDDBClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, MDDB_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) AddBatch(ctx context.Context, in *AddBatchRequest, opts ...grpc.CallOption) (*AddBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBatchResponse)
	err := c.cc.Invoke(ctx, MDDB_AddBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBatchResponse)
	err := c.cc.Invoke(ctx, MDDB_DeleteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) UpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*UpdateBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBatchResponse)
	err := c.cc.Invoke(ctx, MDDB_UpdateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, MDDB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MDDB_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MDDB_ServiceDesc.Streams[0], MDDB_Export_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRequest, ExportChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDB_ExportClient = grpc.ServerStreamingClient[ExportChunk]

func (c *mDDBClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, MDDB_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, MDDB_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TruncateResponse)
	err := c.cc.Invoke(ctx, MDDB_Truncate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MDDB_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, MDDB_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorReindex(ctx context.Context, in *VectorReindexRequest, opts ...grpc.CallOption) (*VectorReindexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorReindexResponse)
	err := c.cc.Invoke(ctx, MDDB_VectorReindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorStats(ctx context.Context, in *VectorStatsRequest, opts ...grpc.CallOption) (*VectorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorStatsResponse)
	err := c.cc.Invoke(ctx, MDDB_VectorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ImportURL(ctx context.Context, in *ImportURLRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, MDDB_ImportURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, MDDB_SetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) FTS(ctx context.Context, in *FTSRequest, opts ...grpc.CallOption) (*FTSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FTSResponse)
	err := c.cc.Invoke(ctx, MDDB_FTS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, MDDB_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookProto)
	err := c.cc.Invoke(ctx, MDDB_RegisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, MDDB_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebhookResponse)
	err := c.cc.Invoke(ctx, MDDB_DeleteWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) SetSchema(ctx context.Context, in *SetSchemaRequest, opts ...grpc.CallOption) (*SetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSchemaResponse)
	err := c.cc.Invoke(ctx, MDDB_SetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, MDDB_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, MDDB_DeleteSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, MDDB_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ValidateDocument(ctx context.Context, in *ValidateDocumentRequest, opts ...grpc.CallOption) (*ValidateDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateDocumentResponse)
	err := c.cc.Invoke(ctx, MDDB_ValidateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDDBServer is the server API for MDDB service.
// All implementations must embed UnimplementedMDDBServer
// for forward compatibility.
//
// MDDB Service - gRPC API for Markdown Database
type MDDBServer interface {
	// Add or update a document
	Add(context.Context, *AddRequest) (*Document, error)
	// Add or update multiple documents in a single transaction (batch)
	AddBatch(context.Context, *AddBatchRequest) (*AddBatchResponse, error)
	// Delete multiple documents in a single transaction (batch)
	DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error)
	// Update multiple documents in a single transaction (batch)
	UpdateBatch(context.Context, *UpdateBatchRequest) (*UpdateBatchResponse, error)
	// Get a document by key and language
	Get(context.Context, *GetRequest) (*Document, error)
	// Search documents with filters
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Export documents (streaming)
	Export(*ExportRequest, grpc.ServerStreamingServer[ExportChunk]) error
	// Create database backup
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	// Restore database from backup
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// Truncate revision history
	Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error)
	// Get server statistics
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Vector/semantic search using embeddings
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	// Reindex embeddings for a collection
	VectorReindex(context.Context, *VectorReindexRequest) (*VectorReindexResponse, error)
	// Get vector/embedding statistics
	VectorStats(context.Context, *VectorStatsRequest) (*VectorStatsResponse, error)
	// Import document from URL
	ImportURL(context.Context, *ImportURLRequest) (*Document, error)
	// Set TTL on a document
	SetTTL(context.Context, *SetTTLRequest) (*Document, error)
	// Full-text search
	FTS(context.Context, *FTSRequest) (*FTSResponse, error)
	// Hybrid search (combines FTS + vector search)
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// Register a webhook
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookProto, error)
	// List webhooks
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	// Delete a webhook
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error)
	// Set JSON Schema for a collection's metadata validation
	SetSchema(context.Context, *SetSchemaRequest) (*SetSchemaResponse, error)
	// Get JSON Schema for a collection
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// Delete JSON Schema for a collection (disables validation)
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	// List all collection schemas
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// Validate document metadata against collection schema
	ValidateDocument(context.Context, *ValidateDocumentRequest) (*ValidateDocumentResponse, error)
	mustEmbedUnimplementedMDDBServer()
}

// UnimplementedMDDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMDDBServer struct{}

func (UnimplementedMDDBServer) Add(context.Context, *AddRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedMDDBServer) AddBatch(context.Context, *AddBatchRequest) (*AddBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBatch not implemented")
}
func (UnimplementedMDDBServer) DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBatch not implemented")
}
func (UnimplementedMDDBServer) UpdateBatch(context.Context, *UpdateBatchRequest) (*UpdateBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatch not implemented")
}
func (UnimplementedMDDBServer) Get(context.Context, *GetRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMDDBServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMDDBServer) Export(*ExportRequest, grpc.ServerStreamingServer[ExportChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedMDDBServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedMDDBServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedMDDBServer) Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Truncate not implemented")
}
func (UnimplementedMDDBServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedMDDBServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedMDDBServer) VectorReindex(context.Context, *VectorReindexRequest) (*VectorReindexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorReindex not implemented")
}
func (UnimplementedMDDBServer) VectorStats(context.Context, *VectorStatsRequest) (*VectorStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorStats not implemented")
}
func (UnimplementedMDDBServer) ImportURL(context.Context, *ImportURLRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportURL not implemented")
}
func (UnimplementedMDDBServer) SetTTL(context.Context, *SetTTLRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTTL not implemented")
}
func (UnimplementedMDDBServer) FTS(context.Context, *FTSRequest) (*FTSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FTS not implemented")
}
func (UnimplementedMDDBServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedMDDBServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedMDDBServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedMDDBServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedMDDBServer) SetSchema(context.Context, *SetSchemaRequest) (*SetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSchema not implemented")
}
func (UnimplementedMDDBServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedMDDBServer) DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchema not implemented")
}
func (UnimplementedMDDBServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedMDDBServer) ValidateDocument(context.Context, *ValidateDocumentRequest) (*ValidateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateDocument not implemented")
}
func (UnimplementedMDDBServer) mustEmbedUnimplementedMDDBServer() {}
func (UnimplementedMDDBServer) testEmbeddedByValue()              {}

// UnsafeMDDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDDBServer will
// result in compilation errors.
type UnsafeMDDBServer interface {
	mustEmbedUnimplementedMDDBServer()
}

func RegisterMDDBServer(s grpc.ServiceRegistrar, srv MDDBServer) {
	// If the following call pancis, it indicates UnimplementedMDDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MDDB_ServiceDesc, srv)
}

func _MDDB_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_AddBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).AddBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_AddBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).AddBatch(ctx, req.(*AddBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_DeleteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteBatch(ctx, req.(*DeleteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_UpdateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).UpdateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_UpdateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).UpdateBatch(ctx, req.(*UpdateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBServer).Export(m, &grpc.GenericServerStream[ExportRequest, ExportChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDB_ExportServer = grpc.ServerStreamingServer[ExportChunk]

func _MDDB_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Truncate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorReindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorReindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_VectorReindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorReindex(ctx, req.(*VectorReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_VectorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorStats(ctx, req.(*VectorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ImportURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ImportURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_ImportURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ImportURL(ctx, req.(*ImportURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_SetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).SetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_SetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).SetTTL(ctx, req.(*SetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_FTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).FTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_FTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).FTS(ctx, req.(*FTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_RegisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_DeleteWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_SetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).SetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_SetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).SetSchema(ctx, req.(*SetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_DeleteSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ValidateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ValidateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDB_ValidateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ValidateDocument(ctx, req.(*ValidateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDDB_ServiceDesc is the grpc.ServiceDesc for MDDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mddb.MDDB",
	HandlerType: (*MDDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MDDB_Add_Handler,
		},
		{
			MethodName: "AddBatch",
			Handler:    _MDDB_AddBatch_Handler,
		},
		{
			MethodName: "DeleteBatch",
			Handler:    _MDDB_DeleteBatch_Handler,
		},
		{
			MethodName: "UpdateBatch",
			Handler:    _MDDB_UpdateBatch_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MDDB_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MDDB_Search_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MDDB_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _MDDB_Restore_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _MDDB_Truncate_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _MDDB_Stats_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _MDDB_VectorSearch_Handler,
		},
		{
			MethodName: "VectorReindex",
			Handler:    _MDDB_VectorReindex_Handler,
		},
		{
			MethodName: "VectorStats",
			Handler:    _MDDB_VectorStats_Handler,
		},
		{
			MethodName: "ImportURL",
			Handler:    _MDDB_ImportURL_Handler,
		},
		{
			MethodName: "SetTTL",
			Handler:    _MDDB_SetTTL_Handler,
		},
		{
			MethodName: "FTS",
			Handler:    _MDDB_FTS_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _MDDB_HybridSearch_Handler,
		},
		{
			MethodName: "RegisterWebhook",
			Handler:    _MDDB_RegisterWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _MDDB_ListWebhooks_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _MDDB_DeleteWebhook_Handler,
		},
		{
			MethodName: "SetSchema",
			Handler:    _MDDB_SetSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _MDDB_GetSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _MDDB_DeleteSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _MDDB_ListSchemas_Handler,
		},
		{
			MethodName: "ValidateDocument",
			Handler:    _MDDB_ValidateDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _MDDB_Export_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mddb.proto",
}

const (
	MDDBReplication_RequestSnapshot_FullMethodName   = "/mddb.MDDBReplication/RequestSnapshot"
	MDDBReplication_StreamBinlog_FullMethodName      = "/mddb.MDDBReplication/StreamBinlog"
	MDDBReplication_ReplicationStatus_FullMethodName = "/mddb.MDDBReplication/ReplicationStatus"
	MDDBReplication_AcknowledgeLSN_FullMethodName    = "/mddb.MDDBReplication/AcknowledgeLSN"
)

// MDDBReplicationClient is the client API for MDDBReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDDBReplicationClient interface {
	// RequestSnapshot streams a full database snapshot to a follower
	RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
	// StreamBinlog streams binlog entries from a given LSN (long-lived server-stream)
	StreamBinlog(ctx context.Context, in *StreamBinlogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BinlogEntryProto], error)
	// ReplicationStatus returns the current replication state of this node
	ReplicationStatus(ctx context.Context, in *ReplicationStatusRequest, opts ...grpc.CallOption) (*ReplicationStatusResponse, error)
	// AcknowledgeLSN allows a follower to confirm it has applied up to a given LSN
	AcknowledgeLSN(ctx context.Context, in *AcknowledgeLSNRequest, opts ...grpc.CallOption) (*AcknowledgeLSNResponse, error)
}

type mDDBReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewMDDBReplicationClient(cc grpc.ClientConnInterface) MDDBReplicationClient {
	return &mDDBReplicationClient{cc}
}

func (c *mDDBReplicationClient) RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MDDBReplication_ServiceDesc.Streams[0], MDDBReplication_RequestSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDBReplication_RequestSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

func (c *mDDBReplicationClient) StreamBinlog(ctx context.Context, in *StreamBinlogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BinlogEntryProto], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MDDBReplication_ServiceDesc.Streams[1], MDDBReplication_StreamBinlog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBinlogRequest, BinlogEntryProto]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDBReplication_StreamBinlogClient = grpc.ServerStreamingClient[BinlogEntryProto]

func (c *mDDBReplicationClient) ReplicationStatus(ctx context.Context, in *ReplicationStatusRequest, opts ...grpc.CallOption) (*ReplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationStatusResponse)
	err := c.cc.Invoke(ctx, MDDBReplication_ReplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBReplicationClient) AcknowledgeLSN(ctx context.Context, in *AcknowledgeLSNRequest, opts ...grpc.CallOption) (*AcknowledgeLSNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeLSNResponse)
	err := c.cc.Invoke(ctx, MDDBReplication_AcknowledgeLSN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDDBReplicationServer is the server API for MDDBReplication service.
// All implementations must embed UnimplementedMDDBReplicationServer
// for forward compatibility.
type MDDBReplicationServer interface {
	// RequestSnapshot streams a full database snapshot to a follower
	RequestSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	// StreamBinlog streams binlog entries from a given LSN (long-lived server-stream)
	StreamBinlog(*StreamBinlogRequest, grpc.ServerStreamingServer[BinlogEntryProto]) error
	// ReplicationStatus returns the current replication state of this node
	ReplicationStatus(context.Context, *ReplicationStatusRequest) (*ReplicationStatusResponse, error)
	// AcknowledgeLSN allows a follower to confirm it has applied up to a given LSN
	AcknowledgeLSN(context.Context, *AcknowledgeLSNRequest) (*AcknowledgeLSNResponse, error)
	mustEmbedUnimplementedMDDBReplicationServer()
}

// UnimplementedMDDBReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMDDBReplicationServer struct{}

func (UnimplementedMDDBReplicationServer) RequestSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Errorf(codes.Unimplemented, "method RequestSnapshot not implemented")
}
func (UnimplementedMDDBReplicationServer) StreamBinlog(*StreamBinlogRequest, grpc.ServerStreamingServer[BinlogEntryProto]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBinlog not implemented")
}
func (UnimplementedMDDBReplicationServer) ReplicationStatus(context.Context, *ReplicationStatusRequest) (*ReplicationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicationStatus not implemented")
}
func (UnimplementedMDDBReplicationServer) AcknowledgeLSN(context.Context, *AcknowledgeLSNRequest) (*AcknowledgeLSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeLSN not implemented")
}
func (UnimplementedMDDBReplicationServer) mustEmbedUnimplementedMDDBReplicationServer() {}
func (UnimplementedMDDBReplicationServer) testEmbeddedByValue()                         {}

// UnsafeMDDBReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDDBReplicationServer will
// result in compilation errors.
type UnsafeMDDBReplicationServer interface {
	mustEmbedUnimplementedMDDBReplicationServer()
}

func RegisterMDDBReplicationServer(s grpc.ServiceRegistrar, srv MDDBReplicationServer) {
	// If the following call pancis, it indicates UnimplementedMDDBReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MDDBReplication_ServiceDesc, srv)
}

func _MDDBReplication_RequestSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBReplicationServer).RequestSnapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDBReplication_RequestSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

func _MDDBReplication_StreamBinlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBinlogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBReplicationServer).StreamBinlog(m, &grpc.GenericServerStream[StreamBinlogRequest, BinlogEntryProto]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDDBReplication_StreamBinlogServer = grpc.ServerStreamingServer[BinlogEntryProto]

func _MDDBReplication_ReplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBReplicationServer).ReplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDBReplication_ReplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBReplicationServer).ReplicationStatus(ctx, req.(*ReplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDBReplication_AcknowledgeLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeLSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBReplicationServer).AcknowledgeLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MDDBReplication_AcknowledgeLSN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBReplicationServer).AcknowledgeLSN(ctx, req.(*AcknowledgeLSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDDBReplication_ServiceDesc is the grpc.ServiceDesc for MDDBReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDDBReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mddb.MDDBReplication",
	HandlerType: (*MDDBReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicationStatus",
			Handler:    _MDDBReplication_ReplicationStatus_Handler,
		},
		{
			MethodName: "AcknowledgeLSN",
			Handler:    _MDDBReplication_AcknowledgeLSN_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestSnapshot",
			Handler:       _MDDBReplication_RequestSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBinlog",
			Handler:       _MDDBReplication_StreamBinlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mddb.proto",
}
